/* eslint-disable */
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { FaLocationArrow } from "react-icons/fa";
import Layout from "~/components/Layout";
//import MagicButton from "~/components/UI/MagicButton";
import animationData from "../data/confetti.json";
import Lottie from "react-lottie";
import { IoCopyOutline } from "react-icons/io5";
import Image from "next/image";
import { motion } from "framer-motion";

const Home: NextPage = () => {

const [copied, setCopied] = useState(false);

const defaultOptions = {
  loop: copied,
  autoplay: copied,
  animationData: animationData,
  rendererSettings: {
    preserveAspectRatio: "xMidYMid slice",
  },
};

const handleCopy = () => {
  const text = "So11111111111111111111111111111111111111112";
  navigator.clipboard.writeText(text);
  setCopied(true);
};
  return (
    <>
      <Head>
        <title>Catistio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="flex h-screen min-h-screen flex-col items-center justify-center bg-black">
          <div className="container flex h-full flex-col items-center justify-center gap-6 px-4 py-16">
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <br></br>
            <div className="flex items-center justify-center space-x-4 pt-40">

                            

                <div className="relative">
                  <motion.div
                    initial={{ opacity: 0, scale: 0 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{
                      type: "tween",
                      duration: 0.2,
                    }}
                  >
                    <Image
                      src="/catio_brown_004.gif" // https://unsplash.com/fr/photos/fzir3jtFuTQ // https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=368&h=368&q=100
                      alt="Catio"
                      width="192"
                      height="192"
                      quality="95"
                      priority={true}
                      className="h-48 w-48 rounded-full object-cover border-[0.35rem] border-white shadow-xl"
                    />
                  </motion.div>

                  <motion.span
                    className="absolute bottom-0 right-0 text-4xl"
                    initial={{ opacity: 0, scale: 0 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{
                      type: "spring",
                      stiffness: 125,
                      delay: 0.1,
                      duration: 0.7,
                    }}
                  >
                    {/*👋*/}
                  </motion.span>
                </div>

                <div className="relative">
                  <motion.div
                    initial={{ opacity: 0, scale: 0 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{
                      type: "tween",
                      duration: 0.2,
                    }}
                  >
                    <Image
                      src="/catio_brown_010.gif" // https://unsplash.com/fr/photos/fzir3jtFuTQ // https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=368&h=368&q=100
                      alt="Catio"
                      width="192"
                      height="192"
                      quality="95"
                      priority={true}
                      className="h-48 w-48 rounded-full object-cover border-[0.35rem] border-white shadow-xl"
                    />
                  </motion.div>

                  <motion.span
                    className="absolute bottom-0 right-0 text-4xl"
                    initial={{ opacity: 0, scale: 0 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{
                      type: "spring",
                      stiffness: 125,
                      delay: 0.1,
                      duration: 0.7,
                    }}
                  >
                    {/*👋*/}
                  </motion.span>
                </div>

                <div className="relative">
                  <motion.div
                    initial={{ opacity: 0, scale: 0 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{
                      type: "tween",
                      duration: 0.2,
                    }}
                  >
                    <Image
                      src="/catio_brown_005.gif" // https://unsplash.com/fr/photos/fzir3jtFuTQ // https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=368&h=368&q=100
                      alt="Catio"
                      width="192"
                      height="192"
                      quality="95"
                      priority={true}
                      className="h-48 w-48 rounded-full object-cover border-[0.35rem] border-white shadow-xl"
                    />
                  </motion.div>

                  <motion.span
                    className="absolute bottom-0 right-0 text-4xl"
                    initial={{ opacity: 0, scale: 0 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{
                      type: "spring",
                      stiffness: 125,
                      delay: 0.1,
                      duration: 0.7,
                    }}
                  >
                    {/*👋*/}
                  </motion.span>
                </div>
              
            </div>
            {/*<h1 className="text-7xl md:text-9xl">Catistio</h1>*/}


              <div className="flex items-center justify-center space-x-4 pt-1">
              <div className="relative">
                  <motion.div
                    initial={{ opacity: 0, scale: 0 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{
                      type: "tween",
                      duration: 0.2,
                    }}
                  >
                    <Image
                      src="/catio_banner_title_003.png" 
                      alt="Catio"
                      width="960"
                      height="960"
                      quality="100"
                      priority={true}
                      className="h-384 w-768 "
                    />
                  </motion.div>

                  <motion.span
                    className="absolute bottom-0 right-0 text-4xl"
                    initial={{ opacity: 0, scale: 0 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{
                      type: "spring",
                      stiffness: 125,
                      delay: 0.1,
                      duration: 0.7,
                    }}
                  >
                    {/*👋*/}
                  </motion.span>
                </div>
              </div>


            <p className="text-center text-lg md:text-2xl">
              $CATIO : <br></br>So11111111111111111111111111111111111111112
            </p>
            <div className="mt-1 relative">
              {/* button border magic from tailwind css buttons  */}
              {/* add rounded-md h-8 md:h-8, remove rounded-full */}
              {/* remove focus:ring-2 focus:ring-slate-400 focus:ring-offset-2 focus:ring-offset-slate-50 */}
              {/* add handleCopy() for the copy the text */}
              <div
                className={`absolute -bottom-5 right-0 ${copied ? "block" : "block"
                  }`}
              >
                {/* <img src="/confetti.gif" alt="confetti" /> 
                <Lottie options={defaultOptions} height={200} width={400} />*/}
              </div>

              {/*<MagicButton
                title={copied ? "CA is Copied!" : "Copy Contract Address"}
                icon={<IoCopyOutline />}
                position="left"
                handleClick={handleCopy}
                otherClasses="!bg-[#161A31]"
              />*/}
            </div>
            <p className="text-center text-lg md:text-2xl">
              Catistio flex right in your wallet.
            </p>

            <Link
              className="rounded-md border-2 border-black bg-[#aaa] px-3 py-2 text-4xl text-black transition-all hover:border-[#aaa] hover:bg-black hover:text-[#aaa]"
              href="https://pump.fun/board"
            >
              Buy !
            </Link>
            <Link
              className="rounded-md border-2 border-black bg-[#aaa] px-3 py-2 text-4xl text-black transition-all hover:border-[#aaa] hover:bg-black hover:text-[#aaa]"
              href="https://dexscreener.com/"
            >
              Chart
            </Link>
            <Link
              className="rounded-md border-2 border-black bg-[#aaa] px-3 py-2 text-4xl text-black transition-all hover:border-[#aaa] hover:bg-black hover:text-[#aaa]"
              href="/emulator"
            >
              Play!
            </Link>
          </div>
        </main>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>

      </Layout>
    </>
  );
};

export default Home;
